### ISSUE TITLE
[]Cardguess giving wrong rewards

### ISSUE THREAD

**Issue by Lgwowo** [DiscordCards/Tracker#6]
https://images.discordapp.net/.eJwFwdENhCAMANBdGIAWBAG3IUjQnLYEavy43O733lc941KbOkT63AD2cxYeu57CI7eqG3O7au7n1IVvyCK5HHclmWCjXdFjDM6nhMY5BJuWGBYT4poCYjDo4aEP8Uu6U1O_PwgEIuE.W4VvCcCfPn_bM1gMZkIS1ugbh4s?width=400&height=276

**Comment by Snazzah** [comment]
This was due to connectivity issues, this has since been resolved.
